name: koc-tournament

services:
  bot:
    image: koc-tournament:latest
    build: .

    environment:
      DISCORD_BOT_TOKEN:
      DISCORD_BOT_CLIENT_ID:
      DISCORD_GUILD_ID:
      DISCORD_TOURNAMENT_ORGANIZER_ROLE_ID:

      DISCORD_TOURNAMENT_ORGANIZER_CHANNEL_ID:
      DISCORD_TOURNAMENT_SIGNUP_CHANNEL_ID:

      DISCORD_SERVER_STATUS_CHANNEL_ID:
      DISCORD_SERVER_STATUS_MESSAGE_ID:
      DISCORD_TWITCH_STREAM_CHANNEL_ID:
      DISCORD_TWITCH_STREAM_MESSAGE_ID:
      DISCORD_TWITCH_STREAM_NOTIFICATION_ROLE_ID:

      DISCORD_CONTENT_SQUAD_ROLE_ID:
      DISCORD_DEVELOPER_ROLE_ID:

      DISCORD_MESSAGE_UPDATE_INTERVAL: 120000

      TWITCH_ID:
      TWITCH_SECRET:
      TWITCH_TRACKING_UPDATE_INTERVAL: 120000

      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/koc-tournament?schema=public

    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine
    restart: always

    environment:
      POSTGRES_DB: koc-tournament
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
